import { format } from "date-fns";
import { getServerSession } from "next-auth/next";
import type { Session } from "next-auth";
import { redirect } from "next/navigation";

import DashboardShell from "@/components/layout/dashboard-shell";
import { authOptions } from "@/lib/auth";
import { FOREX_PAIRS } from "@/lib/constants";
import { getPairStates, getRecentSignals } from "@/lib/signals";

export default async function DashboardPage() {
  const session = (await (getServerSession as unknown as (
    ...args: unknown[]
  ) => Promise<Session | null>)(authOptions)) as Session | null;
  if (!session?.user) {
    redirect("/login");
  }

  const [signals, pairStates] = await Promise.all([
    getRecentSignals(20),
    getPairStates(),
  ]);

  const trendSummary = pairStates.reduce<Record<string, number>>((acc, item) => {
    if (!item.trend) return acc;
    acc[item.trend] = (acc[item.trend] ?? 0) + 1;
    return acc;
  }, {});

  const nextEntry = signals
    .map((signal) => {
      const metadata = signal.metadata;
      const nextEntryTime = metadata?.nextEntryTime
        ? new Date(String(metadata.nextEntryTime))
        : signal.expiresAt ? new Date(signal.expiresAt) : null;
      return nextEntryTime;
    })
    .filter(Boolean)
    .sort((a, b) => (a!.getTime() ?? 0) - (b!.getTime() ?? 0))[0];

  return (
    <DashboardShell>
      <div className="grid gap-6 lg:grid-cols-4">
        <div className="card-surface lg:col-span-2">
          <h2 className="text-lg font-semibold">Current trend snapshot</h2>
          <p className="muted mt-1 text-sm">
            Overview of dominant directional bias across monitored forex pairs.
          </p>
          <div className="mt-6 grid gap-4 sm:grid-cols-3">
            <TrendStat
              label="Bullish"
              value={trendSummary["BULLISH"] ?? 0}
              accent="text-emerald-300"
            />
            <TrendStat
              label="Bearish"
              value={trendSummary["BEARISH"] ?? 0}
              accent="text-rose-300"
            />
            <TrendStat
              label="Range-bound"
              value={trendSummary["RANGE"] ?? 0}
              accent="text-sky-300"
            />
          </div>
        </div>
        <div className="card-surface">
          <h2 className="text-lg font-semibold">Next entry window</h2>
          <p className="muted mt-1 text-sm">
            Estimated time for the next optimal 5-minute entry.
          </p>
          <div className="mt-6 text-2xl font-semibold text-cyan-300">
            {nextEntry
              ? format(nextEntry, "HH:mm aaaa")
              : "Awaiting signal update"}
          </div>
          <p className="muted mt-2 text-xs">
            Signals refresh automatically every 5 minutes.
          </p>
        </div>
        <div className="card-surface">
          <h2 className="text-lg font-semibold">Account</h2>
          <p className="muted mt-1 text-sm">
            {session.user?.email} • {session.user?.role}
          </p>
          <p className="muted mt-4 text-xs">
            Access the admin panel to adjust signal quality and indicator
            sensitivity thresholds.
          </p>
        </div>
      </div>

      <div className="mt-8 grid gap-6 lg:grid-cols-5">
        <div className="card-surface lg:col-span-3">
          <h2 className="text-lg font-semibold">Latest signals</h2>
          <p className="muted mt-1 text-sm">
            The most recent 20 signals generated by the RSI/MACD engine.
          </p>
          <div className="mt-6 overflow-x-auto">
            <table className="min-w-full text-left text-sm">
              <thead className="text-xs uppercase tracking-wider text-slate-400">
                <tr>
                  <th className="py-3 pr-6">Pair</th>
                  <th className="py-3 pr-6">Direction</th>
                  <th className="py-3 pr-6">Quality</th>
                  <th className="py-3 pr-6">RSI</th>
                  <th className="py-3 pr-6">MACD</th>
                  <th className="py-3 pr-6">Generated</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800/70">
                {signals.map((signal) => (
                  <tr key={signal.id} className="hover:bg-slate-900/60">
                    <td className="py-3 pr-6 font-medium text-slate-100">
                      {signal.pair}
                    </td>
                    <td className="py-3 pr-6">
                      <span
                        className={`rounded-lg px-3 py-1 text-xs font-semibold ${
                          signal.direction === "BUY"
                            ? "bg-emerald-500/20 text-emerald-300"
                            : "bg-rose-500/20 text-rose-300"
                        }`}
                      >
                        {signal.direction}
                      </span>
                    </td>
                    <td className="py-3 pr-6 text-slate-200">
                      {signal.quality}%
                    </td>
                    <td className="py-3 pr-6 text-slate-200">
                      {signal.rsi.toFixed(2)}
                    </td>
                    <td className="py-3 pr-6 text-slate-200">
                      {signal.macdHistogram.toFixed(4)}
                    </td>
                    <td className="py-3 pr-6 text-slate-400">
                      {format(new Date(signal.generatedAt), "MMM d, HH:mm")}
                    </td>
                  </tr>
                ))}
                {signals.length === 0 && (
                  <tr>
                    <td
                      className="py-6 text-center text-sm text-slate-400"
                      colSpan={6}
                    >
                      No signals yet. Generate from the admin panel to get
                      started.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </div>

        <div className="card-surface lg:col-span-2">
          <h2 className="text-lg font-semibold">Pair coverage</h2>
          <p className="muted mt-1 text-sm">
            Latest trend classification across monitored forex pairs.
          </p>
          <div className="mt-4 space-y-3">
            {FOREX_PAIRS.map((pair) => {
              const state = pairStates.find((item) => item.pair === pair.pair);
              return (
                <div
                  key={pair.pair}
                  className="flex items-center justify-between rounded-lg border border-slate-800/60 bg-slate-950/60 px-4 py-3"
                >
                  <div>
                    <p className="font-semibold">{pair.pair}</p>
                    <p className="muted text-xs">{pair.description}</p>
                  </div>
                  <div className="text-right text-sm">
                    <p
                      className={`font-semibold ${
                        state?.trend === "BULLISH"
                          ? "text-emerald-300"
                          : state?.trend === "BEARISH"
                            ? "text-rose-300"
                            : state?.trend === "RANGE"
                              ? "text-sky-300"
                              : "text-slate-400"
                      }`}
                    >
                      {state?.trend ?? "UNKNOWN"}
                    </p>
                    <p className="muted text-xs">
                      {state?.lastUpdated
                        ? format(new Date(state.lastUpdated), "HH:mm")
                        : "—"}
                    </p>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </div>
    </DashboardShell>
  );
}

function TrendStat({
  label,
  value,
  accent,
}: {
  label: string;
  value: number;
  accent: string;
}) {
  return (
    <div className="rounded-2xl border border-slate-800/80 bg-slate-950/70 px-5 py-4">
      <p className="muted text-xs uppercase tracking-wide">{label}</p>
      <p className={`mt-2 text-3xl font-semibold ${accent}`}>{value}</p>
    </div>
  );
}
